from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime


class TriageRequest(BaseModel):
    symptoms: str = Field(..., description="Free-text description of symptoms")
    age: int | None = None
    duration: str | None = Field(None, description="e.g. '2 days', '3 hours'")
    existing_conditions: list[str] = Field(default_factory=list)


class TriageResponse(BaseModel):
    urgency: Literal["self_care", "see_doctor_soon", "seek_emergency_care"]
    reasoning: str
    recommended_next_steps: list[str]
    disclaimer: str = (
        "This is not a medical diagnosis. This assessment is generated by an AI "
        "system and is intended for informational purposes only. Consult a "
        "qualified healthcare professional for medical advice."
    )


class JournalEntryCreate(BaseModel):
    content: str


class JournalEntry(BaseModel):
    id: str
    user_id: str
    content: str
    created_at: datetime
