from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime


class TriageRequest(BaseModel):
    symptoms: str = Field(..., description="Free-text description of symptoms")
    age: int | None = None
    duration: str | None = Field(None, description="e.g. '2 days', '3 hours'")
    existing_conditions: list[str] = Field(default_factory=list)


class TriageResponse(BaseModel):
    urgency: Literal["self_care", "see_doctor_soon", "seek_emergency_care"]
    reasoning: str
    recommended_next_steps: list[str]
    disclaimer: str = (
        "This is not a medical diagnosis. This assessment is generated by an AI "
        "system and is intended for informational purposes only. Consult a "
        "qualified healthcare professional for medical advice."
    )


class JournalEntryCreate(BaseModel):
    content: str


class JournalEntry(BaseModel):
    id: str
    user_id: str
    content: str
    created_at: datetime


class MedicationCreate(BaseModel):
    name: str = Field(..., description="Name of the medication (e.g. Aspirin, Ibuprofen)")
    dosage: str | None = Field(None, description="Dosage (e.g. 81mg, 200mg twice daily)")


class MedicationResponse(BaseModel):
    id: str
    user_id: str
    name: str
    dosage: str | None = None
    created_at: datetime


class MedicationCheckResponse(BaseModel):
    medications_checked: list[str]
    has_interactions: bool
    analysis: str
    disclaimer: str = (
        "This is not a medical diagnosis. This assessment is generated by an AI "
        "system and is intended for informational purposes only. Consult a "
        "qualified healthcare professional or pharmacist for medical advice."
    )


class DocumentUploadResponse(BaseModel):
    file_path: str
    filename: str
    chunks_count: int
    message: str


class DocumentAskRequest(BaseModel):
    question: str = Field(..., description="The user's question regarding their uploaded document(s)")


class DocumentAskResponse(BaseModel):
    answer: str
    sources: list[str] = Field(default_factory=list, description="Top-k context chunks retrieved and used to generate answer")
    disclaimer: str = (
        "This is not a medical diagnosis. Information extracted from documents is generated by an AI "
        "system and is intended for informational purposes only. Consult a "
        "qualified healthcare professional to interpret clinical records or lab results."
    )


class DocumentItem(BaseModel):
    file_path: str
    filename: str
    chunks_count: int
    created_at: datetime | None = None


class JournalTrendResponse(BaseModel):
    total_entries: int
    trend_summary: str
    detected_clusters: list[str] = Field(default_factory=list)
    disclaimer: str = (
        "This is not a medical diagnosis. Trend analysis is generated by an AI "
        "system based on user-submitted journal logs for informational purposes only. Consult a "
        "qualified healthcare professional for medical concerns."
    )


class AppointmentCreate(BaseModel):
    provider_name: str = Field(..., description="Name of the healthcare provider or facility")
    appointment_date: str = Field(..., description="ISO 8601 datetime string, e.g. 2024-09-01T10:30:00")
    reason: str = Field(..., description="Reason for the appointment")
    notes: str | None = Field(None, description="Optional pre-visit notes")


class AppointmentUpdate(BaseModel):
    provider_name: str | None = None
    appointment_date: str | None = None
    reason: str | None = None
    notes: str | None = None


class AppointmentResponse(BaseModel):
    id: str
    user_id: str
    provider_name: str
    appointment_date: str
    reason: str
    notes: str | None = None
    created_at: str
