"""
appointments.py — Care Coordination router (Phase F)

Endpoints:
  POST   /appointments                 — log a new appointment
  GET    /appointments                 — list user's appointments
  PATCH  /appointments/{id}            — update appointment (add notes after visit)
  DELETE /appointments/{id}            — remove appointment
  GET    /appointments/summary-pdf     — generate a doctor-ready PDF health summary
"""
from __future__ import annotations

import io
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response

from app.auth import get_current_user
from app.config import settings
from app.database import supabase
from app.models import AppointmentCreate, AppointmentUpdate
from app.services.llm import client

router = APIRouter(prefix="/appointments", tags=["appointments"])

# ──────────────────────────────────────────────────────────────
# CRUD
# ──────────────────────────────────────────────────────────────

@router.post("", status_code=status.HTTP_201_CREATED)
def create_appointment(appt: AppointmentCreate, user_id: str = Depends(get_current_user)):
    result = supabase.table("appointments").insert({
        "user_id": user_id,
        "provider_name": appt.provider_name,
        "appointment_date": appt.appointment_date,
        "reason": appt.reason,
        "notes": appt.notes,
    }).execute()
    if not result.data:
        raise HTTPException(status_code=500, detail="Failed to create appointment.")
    return result.data[0]


@router.get("")
def list_appointments(user_id: str = Depends(get_current_user)):
    result = (
        supabase.table("appointments")
        .select("id, user_id, provider_name, appointment_date, reason, notes, created_at")
        .eq("user_id", user_id)
        .order("appointment_date", desc=False)
        .execute()
    )
    return result.data or []


@router.patch("/{appt_id}")
def update_appointment(
    appt_id: str,
    update: AppointmentUpdate,
    user_id: str = Depends(get_current_user),
):
    patch_data = {k: v for k, v in update.model_dump().items() if v is not None}
    if not patch_data:
        raise HTTPException(status_code=400, detail="No fields to update.")
    result = (
        supabase.table("appointments")
        .update(patch_data)
        .eq("id", appt_id)
        .eq("user_id", user_id)   # scope to owner
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Appointment not found or not authorised.")
    return result.data[0]


@router.delete("/{appt_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_appointment(appt_id: str, user_id: str = Depends(get_current_user)):
    supabase.table("appointments").delete().eq("id", appt_id).eq("user_id", user_id).execute()


# ──────────────────────────────────────────────────────────────
# PDF Summary  — /appointments/summary-pdf
# ──────────────────────────────────────────────────────────────

# Colours (R, G, B)
TEAL  = (15,  61,  58)
CLAY  = (199, 111, 79)
SAGE  = (127, 168, 150)
LIGHT = (246, 243, 236)   # --paper
MUTED = (138, 147, 143)
INK   = (29,  43,  40)


def _build_pdf(
    user_email: str,
    appointments: list[dict],
    medications: list[dict],
    triage_history: list[dict],
    journal_summary: str,
) -> bytes:
    """Builds and returns the PDF as bytes using fpdf2."""
    from fpdf import FPDF

    class VitalPDF(FPDF):
        def header(self):
            # Top accent bar
            self.set_fill_color(*CLAY)
            self.rect(0, 0, 210, 4, "F")
            # Brand + title
            self.set_y(8)
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(*TEAL)
            self.cell(0, 8, "VitalAI", ln=False)
            self.set_font("Helvetica", "", 10)
            self.set_text_color(*MUTED)
            self.cell(0, 8, "  Personal Health Summary", ln=True)
            self.ln(1)
            # Thin rule
            self.set_draw_color(*SAGE)
            self.set_line_width(0.3)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(3)

        def footer(self):
            self.set_y(-16)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(*MUTED)
            self.multi_cell(
                0, 4,
                "Generated by VitalAI, an AI-assisted personal health tool. "
                "Not a substitute for professional medical records. "
                "Always consult a qualified healthcare professional for medical advice.",
                align="C",
            )
            self.set_font("Helvetica", "", 7)
            self.cell(0, 4, f"Page {self.page_no()}", align="C")

        def section_header(self, title: str):
            self.ln(4)
            self.set_fill_color(*TEAL)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 9)
            self.cell(0, 7, f"  {title.upper()}", ln=True, fill=True)
            self.set_text_color(*INK)
            self.ln(2)

        def kv_row(self, key: str, value: str):
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(*TEAL)
            self.cell(42, 6, key, ln=False)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*INK)
            self.multi_cell(0, 6, value or "—")

    pdf = VitalPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_margins(14, 18, 14)

    # ── Meta header ──────────────────────────────────────────
    now_str = datetime.now(tz=timezone.utc).strftime("%d %B %Y, %H:%M UTC")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, f"Patient: {user_email}", ln=False)
    pdf.cell(0, 5, f"Generated: {now_str}", ln=True, align="R")
    pdf.ln(1)

    # ── Appointments ─────────────────────────────────────────
    pdf.section_header("Appointments")
    if not appointments:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 6, "No appointments logged.", ln=True)
    else:
        now_dt = datetime.now(tz=timezone.utc)
        upcoming = [a for a in appointments if _parse_dt(a["appointment_date"]) >= now_dt]
        past     = [a for a in appointments if _parse_dt(a["appointment_date"]) <  now_dt]

        for section_label, items in [("Upcoming", upcoming[:3]), ("Recent Past", past[:3])]:
            if not items:
                continue
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*SAGE)
            pdf.cell(0, 5, section_label, ln=True)
            for a in items:
                dt_str = _fmt_dt(a["appointment_date"])
                pdf.kv_row("Provider", a["provider_name"])
                pdf.kv_row("Date", dt_str)
                pdf.kv_row("Reason", a["reason"])
                if a.get("notes"):
                    pdf.kv_row("Notes", a["notes"])
                pdf.set_draw_color(*LIGHT)
                pdf.set_line_width(0.2)
                pdf.line(14, pdf.get_y() + 1, 196, pdf.get_y() + 1)
                pdf.ln(3)

    # ── Current Medications ──────────────────────────────────
    pdf.section_header("Current Medications")
    if not medications:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 6, "No medications logged.", ln=True)
    else:
        # Table header
        pdf.set_fill_color(*LIGHT)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*TEAL)
        pdf.cell(90, 7, "Medication", border=0, fill=True)
        pdf.cell(90, 7, "Dosage / Frequency", border=0, fill=True, ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*INK)
        for i, med in enumerate(medications):
            fill = (i % 2 == 0)
            if fill:
                pdf.set_fill_color(248, 246, 241)
            pdf.cell(90, 6, med["name"], border=0, fill=fill)
            pdf.cell(90, 6, med.get("dosage") or "—", border=0, fill=fill, ln=True)
        pdf.ln(2)

    # ── Recent Triage History ────────────────────────────────
    pdf.section_header("Recent Symptom Assessments (last 3)")
    if not triage_history:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 6, "No triage assessments recorded.", ln=True)
    else:
        URGENCY_COLORS = {
            "self_care":             (61, 122, 92),
            "see_doctor_soon":       (184, 130, 58),
            "seek_emergency_care":   (165, 67, 42),
        }
        URGENCY_LABELS = {
            "self_care":             "Self Care",
            "see_doctor_soon":       "See Doctor Soon",
            "seek_emergency_care":   "Seek Emergency Care",
        }
        for t in triage_history[:3]:
            urg = t.get("urgency", "")
            color = URGENCY_COLORS.get(urg, INK)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*color)
            label = URGENCY_LABELS.get(urg, urg.replace("_", " ").title())
            dt_str = _fmt_dt(t.get("created_at", ""))
            pdf.cell(0, 6, f"[{label}]  {dt_str}", ln=True)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*INK)
            symptoms_snippet = (t.get("symptoms") or "")[:220]
            if len(t.get("symptoms", "")) > 220:
                symptoms_snippet += "…"
            pdf.multi_cell(0, 5, symptoms_snippet)
            pdf.ln(2)

    # ── Journal Trend Summary ────────────────────────────────
    if journal_summary:
        pdf.section_header("Recent Journal Health Trends (AI Summary)")
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(60, 75, 70)
        # Trim to ~600 chars for PDF
        snippet = journal_summary[:600] + ("…" if len(journal_summary) > 600 else "")
        pdf.multi_cell(0, 5, snippet)
        pdf.ln(2)

    return bytes(pdf.output())


def _parse_dt(s: str) -> datetime:
    """Parse ISO datetime string, always return timezone-aware datetime."""
    try:
        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return datetime.min.replace(tzinfo=timezone.utc)


def _fmt_dt(s: str) -> str:
    try:
        dt = _parse_dt(s)
        return dt.strftime("%d %b %Y, %H:%M")
    except Exception:
        return s or "—"


@router.get("/summary-pdf")
def get_summary_pdf(user_id: str = Depends(get_current_user)):
    """
    Generates a doctor-ready PDF health summary combining:
      - Upcoming / recent appointments
      - Current medication list
      - Last 3 triage assessments
      - LLM-generated journal trend paragraph (if entries exist)
    Returns the PDF as a binary download.
    """
    # 1. Fetch user email for the PDF header (best-effort)
    user_email = user_id
    try:
        user_row = supabase.auth.admin.get_user_by_id(user_id)
        user_email = user_row.user.email or user_id
    except Exception:
        pass  # fallback to user_id as display string

    # 2. Fetch all data in parallel-ish (sequential is fine here — this is a one-shot)
    from datetime import timedelta
    since_90 = (datetime.utcnow() - timedelta(days=90)).isoformat()

    appointments_data = (
        supabase.table("appointments")
        .select("provider_name, appointment_date, reason, notes")
        .eq("user_id", user_id)
        .order("appointment_date", desc=False)
        .execute()
    ).data or []

    medications_data = (
        supabase.table("medications")
        .select("name, dosage")
        .eq("user_id", user_id)
        .execute()
    ).data or []

    triage_data = (
        supabase.table("triage_history")
        .select("urgency, symptoms, created_at")
        .eq("user_id", user_id)
        .gte("created_at", since_90)
        .order("created_at", desc=True)
        .limit(3)
        .execute()
    ).data or []

    # 3. Journal trend summary — generate via LLM if entries exist
    journal_summary = ""
    try:
        journal_records = (
            supabase.table("journal_entries")
            .select("content, created_at")
            .eq("user_id", user_id)
            .order("created_at", desc=True)
            .limit(10)
            .execute()
        ).data or []

        if journal_records:
            bullet_list = "\n".join(
                f"[{r['created_at'][:10]}] {r['content']}"
                for r in journal_records[:8]
            )
            resp = client.chat.completions.create(
                model=settings.llm_model,
                max_tokens=200,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a clinical note assistant. Summarise the patient's recent health journal "
                            "entries in one concise paragraph (3-5 sentences) for a clinician. Be factual, "
                            "neutral, and highlight any recurring symptoms or mood patterns."
                        ),
                    },
                    {"role": "user", "content": bullet_list},
                ],
            )
            journal_summary = resp.choices[0].message.content or ""
    except Exception:
        journal_summary = ""   # best-effort — don't fail the PDF

    # 4. Build PDF
    try:
        pdf_bytes = _build_pdf(
            user_email=user_email,
            appointments=appointments_data,
            medications=medications_data,
            triage_history=triage_data,
            journal_summary=journal_summary,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {e}")

    date_str = datetime.utcnow().strftime("%Y%m%d")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="vitalaai-health-summary-{date_str}.pdf"',
            "Content-Length": str(len(pdf_bytes)),
        },
    )
